apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: resnet-classifier-system
  name: resnet-service-monitor
spec:
  selector:
    matchLabels:
      app: resnet-classifier-system
  podMetricsEndpoints:
    - port: metrics
