apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-classifier-system
  labels:
    app: resnet-classifier-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-classifier-system
  template:
    metadata:
      labels:
        app: resnet-classifier-system
    spec:
      imagePullSecrets:
        - name: ghcrkey
      containers:
        - name: system
          image: ghcr.io/ahmadhamid/resnet_imagenet_classifier:system_develop
          imagePullPolicy: Always
          env:
            - name: "RN_MODELSIZE"
              value: "50"
          ports:
            - name: system
              containerPort: 5000
            - name: metrics
              containerPort: 8081
          # resources:
          #   limits:
          #     cpu: "3000m"
          #   requests:
          #     cpu: "3000m"
