apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-classifier-system
  labels:
    resnet: system
spec:
  replicas: 1
  selector:
    matchLabels:
      resnet: system
  template:
    metadata:
      labels:
        resnet: system
    spec:
      containers:
        - name: system
          image: ghcr.io/ahmadhamid/resnet_imagenet_classifier:system_develop
          imagePullSecrets:
            - name: ghcrkey
          imagePullPolicy: Always
          ports:
            - name: system
              containerPort: 5000
          # resources:
          #   limits:
          #     cpu: "3000m"
          #   requests:
          #     cpu: "3000m"
