apiVersion: v1
kind: Service
metadata:
  name: resnet-classifier
spec:
  selector:
    resnet: system
  type: NodePort
  ports:
    - port: 5000
      targetPort: system
      nodePort: 30500
    - port: 8081
      targetPort: metrics
