apiVersion: v1
kind: Service
metadata:
  name: resnet-classifier
spec:
  selector:
    app: resnet-classifier-system
  type: NodePort
  ports:
    - port: 5000
      name: system
      targetPort: system
      nodePort: 30500
    - port: 2112
      name: metrics
      targetPort: metrics
