apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-classifier-system
  labels:
    resnet: system
spec:
  replicas: 1
  selector:
    matchLabels:
      resnet: system
  template:
    metadata:
      labels:
        resnet: system
    spec:
      containers:
        - name: system
          image: ahmadhamid/resnet-system
          resources:
            limits:
              cpu: "3000m"
            requests:
              cpu: "3000m"
